name = "TableTraitsUtils"
uuid = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
version = "1.0.2"

[deps]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
Missings = "0.4.2, 1"
DataValues = "0.4.4"
IteratorInterfaceExtensions = "0.1.1, 1"
TableTraits = "0.3.1, 0.4, 1"

[targets]
test = ["Test"]
